fix: maintenance action
split the action into single conditional steps

diff --git a/.github/actions/maintenance/action.yml b/.github/actions/maintenance/action.yml
--- a/.github/actions/maintenance/action.yml
+++ b/.github/actions/maintenance/action.yml
@@ -28,19 +28,8 @@ inputs:
 runs:
   using: composite
   steps:
-    - name: set command
-      shell: bash
-      id: vars
-      run: |
-        if [ ${{ inputs.enable }} = 'true' ]; then
-          echo "act_command="maintenance 1" >> $GITHUB_OUTPUT"
-          echo "act_warn_message="Could not enable maintenance mode!" >> $GITHUB_OUTPUT"
-        else
-          echo "act_command="maintenance 0" >> $GITHUB_OUTPUT"
-          echo "act_warn_message="Could not disable maintenance mode!" >> $GITHUB_OUTPUT"
-        fi
-
-    - name: 'Enable/Disable maintenance mode'
+    - name: 'Enable maintenance mode'
+      if: ${{ inputs.enable == 'true' }}
       uses: appleboy/ssh-action@v1.2.5
       with:
         host: ${{ inputs.SSH_HOST }}
@@ -50,13 +39,42 @@ runs:
         timeout: "30s"
         script: |
           cd ${{ inputs.deployment-compose-target }}/
+
           # Check if container is running before running maintenance command
           if docker compose ps --status=running ${{ inputs.container-name }} | grep -q '${{ inputs.container-name }}'; then
-            docker compose exec ${{ inputs.container-name }} sh -c '${{ steps.vars.outputs.act_command }}'
+            docker compose exec ${{ inputs.container-name }} sh -c 'maintenance 1'
             if [ $? != 0 ]
             then
-              echo "WARN: ${{ steps.vars.outputs.act_warn_message }}"
+              echo "WARN: Could not enable maintenance mode!"
               echo "WARN: Proceeding with deployment..."
+            else
+              echo "Maintenance mode enabled"
+            fi
+          else
+            echo "${{ inputs.container-name }} container is not running, skipping maintenance command"
+          fi
+
+    - name: 'Disable maintenance mode'
+      if: ${{ inputs.enable == 'false' }}
+      uses: appleboy/ssh-action@v1.2.5
+      with:
+        host: ${{ inputs.SSH_HOST }}
+        username: ${{ inputs.SSH_USERNAME }}
+        key: ${{ inputs.SSH_KEY }}
+        port: ${{ inputs.SSH_PORT }}
+        timeout: "30s"
+        script: |
+          cd ${{ inputs.deployment-compose-target }}/
+
+          # Check if container is running before running maintenance command
+          if docker compose ps --status=running ${{ inputs.container-name }} | grep -q '${{ inputs.container-name }}'; then
+            docker compose exec ${{ inputs.container-name }} sh -c 'maintenance 0'
+            if [ $? != 0 ]
+            then
+              echo "WARN: Could not disable maintenance mode!"
+              echo "WARN: Proceeding with deployment..."
+            else
+              echo "Maintenance mode disabled"
             fi
           else
             echo "${{ inputs.container-name }} container is not running, skipping maintenance command"
